# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Resilio,Inc.ResilioSync
PackageVersion: 3.0.1.1414
InstallerType: exe
InstallerSwitches:
  Silent: /S
Installers:
- InstallerUrl: https://download-cdn.resilio.com/stable/windows/64/0/Resilio-Sync_x64.exe
  Architecture: x64
  InstallerSha256: B7CD0321756416BF8B476FE139456A1E7B199A73696E58EB2C1C81B46F152F37
ManifestType: installer
ManifestVersion: 1.6.0
